### ISSUE TITLE
文件上传报错 callback twice

### ISSUE THREAD

**Issue by mocuishlelin** [gp5251/webpack-aliyun-oss#21]
报错日志：
[urllib:warn] [Mon Aug 01 2022 10:21:58 GMT+0800 (China Standard Time)] [25] [worker:2479] PUT https://xxxxxxxxx.aliyuncs.com/xxxx/118377/2d4a9c7.js callback twice!!!
[urllib:warn] [Mon Aug 01 2022 10:21:58 GMT+0800 (China Standard Time)] [25] [worker:2479] ResponseError: premature close
stack: ResponseError: premature close
    at onclosenexttick (/xxxxxxxxxx/node_modules/end-of-stream/index.js:54:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
请问有人遇到过吗，如何解决呢？

**Comment by Lionad-Morotar** [comment]
检查一下是不是 region 填错了，我从 “cn-shanghai” 改成 “oss-cn-shanghai” 就好了

**Comment by GoldenZqqq** [comment]
遇到了同样的问题 region填的也没问题 请问解决了吗
